### ISSUE TITLE
How about benchmark?

### ISSUE THREAD

**Issue by jmas** [tbranyen/diffhtml#101]
Hello. I guess developers want to know a real benchmark numbers when they take DiffHTML.
We need to write some benchmarks and show cases where DiffHTML is good and bad.

For example, I wrote simple benchmark here (I compare DiffHTML with browser innerHTML and with morphdom): https://gist.github.com/jmas/c7c11f1431bf97f0333d6da639b0c0cd

Maybe someone can add other DOM patch libraries to this benchmark or write better one.

Thanks.

**Comment by tbranyen** [comment]
Hey @jmas mind adding this as a comment to: https://github.com/tbranyen/diffhtml/issues/85 and closing this (its sort of a dupe).
