### ISSUE TITLE
Re-executing js scripts

### ISSUE THREAD

**Issue by rahmanusta** [tbranyen/diffhtml#12]
Hello @tbranyen ;

Thanks for your great work diffhtml again. I'm using it in AsciidocFX editor. Editing HTML and CSS  is ok but I need to re-execute JavaScript codes after they changed. How can we do that with diffhtml ?

THanks

**Comment by tbranyen** [comment]
Hey @rahmanusta I'm not sure this is something we can do.  You might be able to just write some DOM code that finds the script tags and then evals the contents.  Let me know what you come up with!

**Comment by rahmanusta** [comment]
@tbranyen If you can give me a hook when script element or it's content changed, I think I can handle that issue.

**Comment by tbranyen** [comment]
@rahmanusta I'm working on the next version of diffhtml and I think this will possible with the transition API.  It would look something like:

``` javascript
document.documentElement.transitionStates = {
  added: function(newElement) {
    if (newElement.matches('script')) {
      // Do something to the script element.
    }
  }
};
```

Do you think that'd work for you?

**Comment by tbranyen** [comment]
I'm going to work a bit more on this API, I think it should work more like `addEventListener`.  As you may want to set many transitions from different places in your code.  Maybe:

``` javascript
document.body.addTransitionState('added', function(newElement) {
  if (newElement.matches('script') {
      // Do something to the script element, maybe eval?
  }
});
```

**Comment by tbranyen** [comment]
Documenting my thoughts on the API here: https://github.com/tbranyen/diffhtml/issues/14

**Comment by rahmanusta** [comment]
@tbranyen , the Transition API may help me for the need. I will try that!

**Comment by tbranyen** [comment]
I haven't fully written it yet, but hopefully I'll have a beta today you can try!

**Comment by rahmanusta** [comment]
Thank you @tbranyen !

**Comment by tbranyen** [comment]
@rahmanusta https://github.com/tbranyen/diffhtml/blob/1eeeadcb179e4357bcc55fc48641f420f0a2223d/dist/diffhtml.js you could try using that, but you'll have to do the following now:

```
diff.enableProllyfill();

// You'll probably want to disable the Web Worker for now, it's been acting a bit strange and needs more testing.
document.DISABLE_WORKER = true;
```

You'll then want to convert your assignments from `someElement.diffHTML = '...';` to either:

- `someElement.diffOuterHTML` to diff the current element and all children or
- `someElement.diffInnerHTML` to diff the current element's children only or
- `someElement.diffElement(someOtherElement)` to diff the current element against a different element

From there you can register a transition and test if you can access the script source:

``` javascript
someElement.addTransitionState('added', function(newElement) {
  if (newElement.matches('script')) {
    console.log('Do something with the script here...');
  }
});
```

**Comment by rahmanusta** [comment]
Thank you @tbranyen . I tried but I'm getting SyntaxError: Invalid regular expression: nothing to repeat

**Comment by tbranyen** [comment]
Hrm darn, can you provide more error context.  Line # ,stack trace, etc.

**Comment by rahmanusta** [comment]
@tbranyen It seems caused my mistake. added hook is running when an element added to DOM. So is there a way to hook script's src attribute and  it's  content changed ?

**Comment by tbranyen** [comment]
Okay so you need attribute transitions as well.  I'll add that later today and ping you.  It should be trivial.  I'd imagine the API would look like:

``` javascript
someElement.addTransitionState('attributeChanged', function(element, attributeName) {
  if (element.matches('script') && attributeName === 'src') {
    console.log('Script source changed');
  }
});
```

I'll mess with the idea, might end up with `addAttributeTransitionState` that mirrors the element API, but that might be overkill.

**Comment by rahmanusta** [comment]
Thank you @tbranyen, also note that don't hurry for my needs. But, I will use and will follow up this changes!

**Comment by tbranyen** [comment]
@rahmanusta master has the API described above and https://github.com/tbranyen/diffhtml/blob/master/examples/transitions/script.html shows how you can monitor script text as well.

**Comment by rahmanusta** [comment]
Thank you @tbranyen!

I will try that

**Comment by rahmanusta** [comment]
@tbranyen It seems attached event works well but textChanged seems not. You can try that gist https://gist.github.com/rahmanusta/f097d65b3a496645bac4

**Comment by tbranyen** [comment]
You're using `innerText` there, try `diff.innerHTML`.

``` javascript
    setInterval(function(){
		diff.innerHTML(document.querySelector("style"), "Hello" + Math.random(100));
	},3000);
```

**Comment by rahmanusta** [comment]
@tbranyen  If I surround the text with a HTML element for example "span";

```
setInterval(function(){
 diff.innerHTML(document.querySelector("style"), "<span>Hello" + Math.random(100) +"</span>");
},3000);
```

It works, but we know that style element or script element doesnt accept such a like HTML element.

**Comment by tbranyen** [comment]
Hey @rahmanusta can you try with master? Should look like:

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <style></style>	
  <title>Attribute</title>
</head>
<body>

  <script src="../../dist/diffhtml.js"></script>

  <script>
    var textarea = document.querySelector('textarea');

    diff.addTransitionState('textChanged', function(el, old, current) {
      console.log(el);
      if (el.matches('style')) {
        console.log(current);
      }
    });

    setInterval(function(){
      diff.innerHTML(document.querySelector("style"), "Hello" + Math.random(100));
    },3000);
  </script>
</body>
</html>
```
