### ISSUE TITLE
ReleaseHook for middleware

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#156]
A new middleware hook for when `vTree`s get released from calling `release`. I need a way to ensure consistent cleanup in the components testing repo.

It would work like the following:

``` js
const { innerHTML, use, release } = require('diffhtml');
const { assign } = Object;

use(assign(() => {}, {
  releaseHook(vTree) {
    // Do some additional cleanup with the VTree.
  }
}));

innerHTML(document.body, '<div />');
release(document.body);
```

**Comment by mAAdhaTTah** [comment]
This is something mostly used by tests? Seems straightforward enough. 👍

**Comment by tbranyen** [comment]
Yup! Basically I maintain caches in the diffhtml-components implementation that are separate from the core caches. I want to assert these are properly emptied on a per test basis.
