### ISSUE TITLE
License? Forking, etc

### ISSUE THREAD

**Issue by bevacqua** [tbranyen/diffhtml#2]
Hey, great concept. I'm an environmentalist though, and don't quite like pollution. Is it okay if I fork this into just a `function` instead of a method on a browser prototype?

**Comment by tbranyen** [comment]
Assume MIT, I'll add it in later

**Comment by bevacqua** [comment]
https://github.com/bevacqua/diferente, added you as a collaborator in case you're interested in the modular approach. Thanks
