### ISSUE TITLE
Etiquette - questions here or Discussions?

### ISSUE THREAD

**Issue by yatesco** [tbranyen/diffhtml#238]
Hi there - I just wanted to double check - do you prefer questions here or in Discussions? I notice that until I polluted Discussions with my entries ;-) it was used as a sounding board/notes for yourself and there are a bunch of questions raised as GitHub issues.

Thanks

**Comment by tbranyen** [comment]
Probably discussions would be better if it's for new features or questions not related to an issue. If you have a problem or want to request a feature, I would start with Issues.
