### ISSUE TITLE
executeScripts does not work in Firefox

### ISSUE THREAD

**Issue by cetinsert** [tbranyen/diffhtml#249]
With
```html
<div id=x></div>
<script type=module>
  console.warn(1);
  import { innerHTML } from 'https://diffhtml.org/es';
  innerHTML(x, '<script>console.warn(2)<\/script>');
</script>
```
**Firefox** does not execute scripts!
![image](https://user-images.githubusercontent.com/27027/150164648-3e799626-2d83-4686-a09b-9c9075636f95.png)

while other browsers do
![image](https://user-images.githubusercontent.com/27027/150164822-5ee764b0-1719-438b-a16c-07d615741ecb.png)

---

**Firefox** also does not execute non-inline scripts:

```html
<script src=//test.domain/warn.js></script>
```

---

https://github.com/tbranyen/diffhtml/blob/2eecafe627079154d2011fcec86c3e128236faab/packages/diffhtml/lib/transaction.js#L248-L272

**Comment by cetinsert** [comment]
```html
z = document.createElement('script'); z.textContent = `console.warn(3)`; document.body.append(z);
```
works in all browsers.

**Comment by tbranyen** [comment]
Thanks for bringing up this bug, it's a big one. Very strange that Firefox behaves differently than Chrome here.

The reason we clone a new script vs creating with `createElement` is that when you load the page with a content security policy you won't be able to modify certain scripts after the first page load. Therefore we clone and retain them until they are needed.

It appears Firefox struggles to re-use an existing script once it has been set with a `type` of `no-execute`, unlike Chrome.

**Comment by tbranyen** [comment]
Ah, I think I found a workaround. If we clone the original script before we attach the type change, we should be able to reuse that one later vs cloning at the end of the render.

**Comment by tbranyen** [comment]
Opened a fix here: https://github.com/tbranyen/diffhtml/pull/250. I ended up using your advice to `createElement` and use `textContent`.

**Comment by cetinsert** [comment]
@tbranyen – hopefully this does not introduce regressions with all the subtle `<script>` variations we have to deal with these days. (`type=module`; inline vs via `src=`; `defer`, `async`; etc.)

**Comment by cetinsert** [comment]
Once you confirm and close this issue. I will be looking forward to a new CDN (`module`) link including this fix!

**Comment by tbranyen** [comment]
> @tbranyen – hopefully this does not introduce regressions with all the subtle `<script>` variations we have to deal with these days. (`type=module`; inline vs via `src=`; `defer`, `async`; etc.)

All original props and attributes are mirrored so I think we are covered on that front :+1:

**Comment by tbranyen** [comment]
https://diffhtml.org/core/version points to 1.0.0-beta.23 now which contains the fix. Please reopen if you find any issues with the new behavior.

Thanks for reporting!
