### ISSUE TITLE
delete in removeAttribute causes TypeError

### ISSUE THREAD

**Issue by cetinsert** [tbranyen/diffhtml#261]
Please note that in the following only the second `delete` is in a `try` `catch`:

https://github.com/tbranyen/diffhtml/blob/cab7fb3ce9da8d12e32d10c7d15182f1b08856d9/packages/diffhtml/lib/node/patch.js#L87-L105

The first `delete` in

https://github.com/tbranyen/diffhtml/blob/cab7fb3ce9da8d12e32d10c7d15182f1b08856d9/packages/diffhtml/lib/node/patch.js#L94

causes https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_delete exceptions for some web components that implement attribute ↔ property reflection with `Object.defineProperty`.

**Comment by tbranyen** [comment]
Can you post an example of what is breaking? The first delete is not in a try/catch intentionally for performance reasons. This code attempts to delete a property and if it succeeds, marks that property as safe for a given tag name. That's the only way the first delete will be reached.

**Comment by cetinsert** [comment]
Here is an absolutely minimal case: https://tw.uido.co/test/index.html

```html
<script src="//webpdf.co/<>" type=module></script>

<pdf-file id=f src=//pdf.ist/web.pdf></pdf-file>
<div      id=i><pdf-page off=f></pdf-page></div>

<script type=module>
  import * as diff from '//esm.run/diffhtml'; window.diff = diff;
  await customElements.whenDefined('pdf-page');
  await diff.innerHTML(i, `<pdf-page of=f></pdf-page>`);
  await diff.innerHTML(i, `<pdf-page off=f></pdf-page>`); // TypeError
</script>
```

**Comment by cetinsert** [comment]
@tbranyen – I have demoed and described the problem/solution in the above 2 comments.

**Comment by tbranyen** [comment]
Fix opened here @cetinsert https://github.com/tbranyen/diffhtml/pull/262

**Comment by tbranyen** [comment]
Darnit, so my Travis CI account just ran out of open source credits. My account should reset in an hour and a half when the new month starts. Would be awesome to convert this project to GitHub Actions CI infra instead.

**Comment by tbranyen** [comment]
Released in https://github.com/tbranyen/diffhtml/releases/tag/v1.0.0-beta.27
