### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#30]
Moved to PR #52

**Comment by tbranyen** [comment]
Also the SVG one hurts my eyes, so I'm thinking a nicer looking one with the boxes just bouncing around slightly transparent will be much better.

**Comment by jmeas** [comment]
I'm down to try my hand at putting together some of these examples. It'd be a cool learning exercise to figure out more about the lib. Think now's a good time to do this, or are there any big refactors coming?

**Comment by tbranyen** [comment]
There will be a lot of refactors, but the API is pretty much locked. We could go to 1.0 as soon as we're happy with the performance and the web worker implementation.

**Comment by tbranyen** [comment]
Although a site, better documentation, and examples would probably be good to have too :sunglasses:

**Comment by tbranyen** [comment]
We have a site now, available at http://diffhtml.org with a few examples. Unfortunately they aren't very useful. We should turn them into standalone JSFiddle's or similar and embed.
