### ISSUE TITLE
Configure `npm test` to not have git side effects

### ISSUE THREAD

**Issue by jmeas** [tbranyen/diffhtml#36]
I cloned the lib, ran `npm i`, then ran `npm test` to make sure that the tests passed locally. They did, but it also built `dist/diffhtml.js`, which git recognized as a change.

I usually prefer to make it so `npm test` has no side effects, which makes it easier for folks to contribute to the library – they can make changes to the src, run the tests, then PR without needing to undo the change to the build. This assumes that ya don't want people PRing the built file, which is usually something I only do when it's release time.

Typically, I accomplish this by building to a tmp directory for the tests that is gitignored. Lmk if this is something you're interested in, and I can make a PR for it.

**Comment by tbranyen** [comment]
Ah okay, so the test command rebuilds the library to include a global `require` method that we hook into to test the library. This is a motivator for switching to AMD/ES5 to avoid this to unit test each part. The alternative here is to build all the tests and run as a single bundle.

**Comment by jmeas** [comment]
> This is a motivator for switching to AMD/ES5 to avoid this to unit test each part.

Makes sense.

> The alternative here is to build all the tests and run as a single bundle.

That's my current strategy, though I only bundle them for the browser version of the tests.

**Comment by tbranyen** [comment]
This has been resolved, no longer needs to rebuild the library in order to test.
