### ISSUE TITLE
Updates to gh-pages

### ISSUE THREAD

**Issue by jmeas** [tbranyen/diffhtml#38]
You prob. already know this, but the gh-pages site seems a lil outdated. I can update it if you give me a list of changes. It seems like the entire "About" section is out of date as of #10.

Things that need updating:

- No dependencies on `virtual-dom`, and, in fact, no dependency on anything
- Optional prollyfill, rather than that being the default
- A description of the algorithm currently employed

I'm still diving into the details of the lib, so I don't think I could write out how the current algo works. Anyway, figured I'd raise the issue.

**Comment by tbranyen** [comment]
Yup, thanks! I want to create a new site (w/ updated content), but first I gotta undo all the damage I've caused from experimenting.

I'm working in the rewrite-amd branch and adding unit tests for each part of the library. For instance I'm not positive all the transitions are working correctly for all the cases. There are tests in place right now that test part of it, but I wasn't able to get code coverage working with ES2015 modules + Babel, hence the switch to AMD/ES5.

**Comment by tbranyen** [comment]
I've since made a brand new site, it's missing some documentation, but we'll add it as we go.
