### ISSUE TITLE
Linting errorz

### ISSUE THREAD

**Issue by jmeas** [tbranyen/diffhtml#39]
You may already know this, but atm you're [only linting files in the root directory](https://github.com/tbranyen/diffhtml/blob/20b954aa484dd69c8229a224c02e8c46b436617d/package.json#L10) of the project. Linting everything via `**/*.js` yields a number of errors.

I'm working on resolving the easy ones, like semicolon problemz, but there will be other issues that might require some more thought.

I'm opening this issue as a placeholder for resolving those problems. Don't worry about it now unless you're super curious; I'll compile a more in-depth analysis once I make a PR based on the conversation @ https://github.com/tbranyen/diffhtml/pull/37#issuecomment-167376970

**Comment by tbranyen** [comment]
Yup those were all fixed in the amd rewrite branch as well :)

**Comment by jmeas** [comment]
Ah, okay, cool. I'll close this issue and look there.

**Comment by tbranyen** [comment]
I'll start backporting my changes into a PR as well

**Comment by tbranyen** [comment]
Ya, I would just ignore the linting for now (for w/e you're doing).
