### ISSUE TITLE
[Question] Browser support / Sauce Labs?

### ISSUE THREAD

**Issue by jmeas** [tbranyen/diffhtml#49]
I'm curious to know what the target browser support is. I don't see it on the site atm.

Also, could be worthwhile to run the tests in SauceLabs. Whatcha think?

**Comment by tbranyen** [comment]
I tried this with Combyne, but found that Saucelabs timed out way too much. Wasn't able to figure out how to make Saucelabs run on PRs either.

If we can solve the timeout issue and make it work on PRs, I'd be definitely down.

**Comment by tbranyen** [comment]
As for browser support, it's true I've skirted around explicitly saying.

**Comment by tbranyen** [comment]
I'd be willing to help out with this. Just tested on latest Firefox, Safari, IE, and Chrome.

Firefox 44:

- Issues with decoding HTML entities, might be related to innerHTML/innerText/textContent

Safari 9:

- No known issues

Chrome 48:

- Attached callback isn't triggered on custom elements that have already been added to the DOM
  - Need to research the specification and then revise/fix our implementation/test

**Comment by tbranyen** [comment]
I've since been added to an open source BrowserStack plan and posted the initial round of browser tests here:
