### ISSUE TITLE
Track Custom Element rewrite changes

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#56]
Reference: https://github.com/w3c/webcomponents/pull/405

Since the Custom Element API is still in flux, I've only implemented the API that matches current browsers. I'll be starting on an opt-in to try out the new API. I'm thinking something like `diff.enableExperimental()` which matches `enableProllyfill()` except brings in the new APIs and will change with the leading browser implementation.

**Comment by tbranyen** [comment]
So much has changed since then... it's gotten a rewrite since the last rewrite. It's out of control so I'm going to rip out of this library until it stabilizes.

**Comment by jmeas** [comment]
slight preference for:

`enableProllyfill({experimental: true});` if this ever comes to be

**Comment by tbranyen** [comment]
Closing this out, since I'm going to leave it to the browser vendors to settle on a standard and then we'll revisit.
