### ISSUE TITLE
data-name parameters are lost after patch

### ISSUE THREAD

**Issue by coderaiser** [tbranyen/diffhtml#6]
When I do :

```js
element.diffHTML = '<div data-name="js-element"></div>';
'<div data-name="js-element"></div>'

element
    .querySelector('div')
    .getAttribute('data-name');
undefined
``` 
In results markup of element there is no `data-name`.

**Comment by tbranyen** [comment]
@coderaiser looks to be a result of:

https://github.com/Raynos/virtual-hyperscript#data-

We may be able to patch over this.

**Comment by tbranyen** [comment]
Patched here: https://github.com/tbranyen/diffhtml/commit/04620904e34f103287538c448338daa6eb191de4#diff-6d186b954a58d5bb740f73d84fe39073R30
