### ISSUE TITLE
Can I use virtual tree directly in my program?

### ISSUE THREAD

**Issue by jiyinyiyong** [tbranyen/diffhtml#65]

**Comment by tbranyen** [comment]
Hi @jiyinyiyong can you explain a little more what you're trying to do?

**Comment by jiyinyiyong** [comment]
I was from React and it was quite fluent to assemble a virtual DOM, while to get HTML string we need one more function like `stringify`. I suppose that `diffhtml` still need to parse may HTML string into a virtual DOM, so if I pass in a virtual DOM will it be faster?

**Comment by tbranyen** [comment]
Yes it will be. In fact I'm working on a babel transform right now to make it precompile them as well.

**Comment by tbranyen** [comment]
If you wanted to manually ingest a dynamic tree you can use the following functions to generate them:

``` javascript
const createElement = (tagName, attributes, childNodes) => ({
  uuid: String(Math.floor(Math.random() * Date.now())),
  nodeName: tagName.toLowerCase(),
  nodeType: 1,
  nodeValue: '',
  attributes: Object.keys(attributes || []).map(
    keyName => ({
      name: keyName,
      value: attributes[keyName]
    })
  ),
  childNodes: childNodes || [],
})

const createTextElement = value => ({
  uuid: String(Math.floor(Math.random() * Date.now())),
  nodeName: '#text',
  nodeType: 3,
  nodeValue: value,
  key: '',
  attributes: [],
  childNodes: [],
})
```

Here's an example of usage:

``` javascript
createElement('div', { class: 'cool-class' }, [
  createElement('p', { onclick(ev) {} }, [
    createTextElement('click me')
  ])
])
```

**Comment by tbranyen** [comment]
To use with diffHTML you'd then pass that value like so:

``` html
<div id="parent"></div>
```

``` javascript
const innerHTML = diff.innerHTML
const element = document.querySelector('#parent')

innerHTML(element, createElement('div', { class: 'cool-class' }, [
  createElement('p', { onclick(ev) {} }, [
    createTextElement('click me')
  ])
]));
```

**Comment by tbranyen** [comment]
@jiyinyiyong Here is an example JSFiddle as well: https://jsfiddle.net/tbranyen/xhbnvna3/1/

Hope all this helps!

**Comment by jiyinyiyong** [comment]
There's even a `onclick` function, that's cool. Thanks.
