### ISSUE TITLE
Would it be possible to see some metrics?

### ISSUE THREAD

**Issue by farzd** [tbranyen/diffhtml#85]
Would it be possible to see some performance metrics, how its better than normal DOM manipulation?

https://developer.mozilla.org/en-US/docs/Web/API/Performance_API

**Comment by tbranyen** [comment]
Sure thing! I will say its not better than normal DOM manip, since that is what gets used in the end anyways.

**Comment by jmas** [comment]
Hello. I guess developers want to know a real benchmark numbers when they take DiffHTML.
We need to write some benchmarks and show cases where DiffHTML is good and bad.

For example, I wrote simple benchmark here (I compare DiffHTML with browser innerHTML and with morphdom): https://gist.github.com/jmas/c7c11f1431bf97f0333d6da639b0c0cd

Maybe someone can add other DOM patch libraries to this benchmark or write better one.

Thanks.

P.S: I found another one benchmark here http://mathieuancelin.github.io/js-repaint-perfs/diffhtml/index.html

**Comment by tbranyen** [comment]
Here are the latest metrics from the preact-perf repository using the latest version of diffHTML and I also updated choo which was unfairly getting poor perf scores.
![choo](https://cloud.githubusercontent.com/assets/181635/23328211/0fa5c422-fad1-11e6-975c-6c214be333a7.png)
