### ISSUE TITLE
Generate TypeScript bindings from documentation API

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#91]
I've created an API documentation generator for diffHTML using NodeGit. This could be used to generate the typings automatically.

Resources:
- http://definitelytyped.org/guides/best-practices.html
- https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

Thanks @mousetraps!

**Comment by mousetraps** [comment]
Nice!! Any chance you could share a link to the generator? I'm sure @DanielRosenwasser would be interested!

**Comment by tbranyen** [comment]
The core codebase has been changed to checkJs, a feature in TyepScript. This allows definitions to be generated directly from the source.
