### ISSUE TITLE
innerHTML() function do not applying checkbox checked state

### ISSUE THREAD

**Issue by jmas** [tbranyen/diffhtml#97]
Hello. I trying to reinvent ToDo app. But have issue with `<input type="checkbox" />` element.

```js
export function createTask (task, index) {
  return html`
    <li>
      <label>
        <input type="checkbox" onclick="${onTaskChange}" value=${index} ${task.done ? 'checked': ''} />
        ${task.name} (${task.done ? 'Done': 'Not Done'})
      </label>
    </li>
  `;
}
```

Here is link where you can see full code listing: https://github.com/jmas/htmldiff-todo/blob/master/src/ui.js#L23

This line is working correctly:
`${task.name} (${task.done ? 'Done': 'Not Done'})`.

But there is a problem:
`<input type="checkbox" onclick="${onTaskChange}" value=${index} ${task.done ? 'checked': ''} />`

**Problem**
Checkbox wan't change checked state, even `task.done` is `true`.

**Update:** If I change input to following structure:
```html
<input type="checkbox" onclick="${onTaskChange}" value=${index} k="${task.done ? 'checked': ''}" />
```
I can see that `k` attribute is changing it state from `(empty)` to `checked`.

**Comment by tbranyen** [comment]
Hrm, @jmas what about this: https://github.com/tbranyen/todomvc/blob/gh-pages/lib/components/todo-list.js#L13

This appears to work fine, I wonder why you were hitting an issue. I noticed your PR, and I'll try and write a unit test to complement it when I get into the office.

**Comment by jmas** [comment]
@tbranyen Thanks!

**Comment by tbranyen** [comment]
https://github.com/tbranyen/diffhtml/pull/102 << check out the two `it.only` tests here

**Comment by jmas** [comment]
@tbranyen I found where was a problem.
It all about how browser process events on buttons `checkbox`, `radio`.
When we doing `event.preventDefault()` browser is prevent checking this element **in current processing loop**. So when I click checkbox the I prevent default browser behavior > change value in store > and I think that checkbox should be checked by value from store, but in doesn't do it.
So my solution is: to modify render:
```
store.subscribe(() => window.requestAnimationFrame(render));
```
Now `checkbox`, `radio` is working as it working in React+Flux.
Thanks for watching us. I close the issue.

**Comment by tbranyen** [comment]
Awesome, glad you were able to figure it out!
