### ISSUE TITLE
Enhance the build

### ISSUE THREAD

**Issue by kltan** [tbranyen/diffhtml#99]
I am thinking that the `/dist` folder should be added to `.gitignore` to reduce the diff noise and `/lib` is added to `.npmignore`. During `prepublish` we add the build script so that it's published to npm.

```
"prepublish": "npm run build && babel lib --source-maps -d dist/cjs"
```

**Comment by kltan** [comment]
@tbranyen If proposal is accepted I can open up a PR.

**Comment by tbranyen** [comment]
@kltan I've used the approach you're describing in quite a few of my other open source projects. The reason why I've stopped doing this for diffHTML and others, is that there is just too much utility in being able to point to a SHA and be able to test immediately.

I have a `.gitattributes` file added that will silence any `dist` files from showing up in local diffs, I really wish @github would support this as well.

**Comment by kltan** [comment]
@tbranyen Ah, makes sense, although it's still a pain in GitHub.

**Comment by tbranyen** [comment]
I totally agree, I really wish it could be nicer. My suggestion would be not to commit the dist files until you're ready to merge/test (if you want better looking diffs).

**Comment by tbranyen** [comment]
Lets keep this open for now though, I'd be interested in hearing if others feel the same way.

**Comment by kltan** [comment]
If ready means bumping the version, the build script probably can be run in `preversion`.

**Comment by tbranyen** [comment]
I'm going to keep as-is for now, it's been more convenient for me developing and the current `.npmignore` and `cjs` build scripts make a pretty flexible distribution.
